# Generated by Django 2.2 on 2021-12-07 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_plan_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='gift',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='maxdeposit',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='maxreturn',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='mindeposit',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='minreturn',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='profit',
            name='ammount',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.CreateModel(
            name='Join_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('price', models.CharField(default='0', max_length=50)),
                ('duration', models.CharField(default='0', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
