# Generated by Django 2.2 on 2021-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211207_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=50)),
                ('wallet', models.CharField(default='0', max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
