# Generated by Django 2.2 on 2021-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay_method',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='pay_method',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
