# Generated by Django 2.2 on 2021-12-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join_plan',
            name='user',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
