# Generated by Django 2.2 on 2022-05-07 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211207_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duration',
            new_name='days',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='gift',
            new_name='profit',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='maxreturn',
            new_name='ref',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='minreturn',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AlterField(
            model_name='join_plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profit',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='user.Plan'),
        ),
    ]
